### ISSUE TITLE
Need for Speed Hot Pursuit Remastered

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2854]
#### Current on `master` : 1.0.5727

Game loads and plays with smooth graphics in-game but with loud, distorted audio.

#### Screenshots :

![2020-11-17 10_30_56-Ryujinx 1 0 5727 - Need For Speed™ Hot Pursuit Remastered v1 0 0 (010029B0118E80](https://user-images.githubusercontent.com/62343878/99427619-e115c980-28c2-11eb-963a-4bdd29b343ac.png)
![2020-11-17 10_32_08-Ryujinx 1 0 5727 - Need For Speed™ Hot Pursuit Remastered v1 0 0 (010029B0118E80](https://user-images.githubusercontent.com/62343878/99427635-e410ba00-28c2-11eb-8e12-133089a9eb76.png)
![2020-11-17 10_33_18-Ryujinx 1 0 5727 - Need For Speed™ Hot Pursuit Remastered v1 0 0 (010029B0118E80](https://user-images.githubusercontent.com/62343878/99427650-e96e0480-28c2-11eb-83d3-7a2f49d7375d.png)
![2020-11-17 10_33_51-Ryujinx 1 0 5727 - Need For Speed™ Hot Pursuit Remastered v1 0 0 (010029B0118E80](https://user-images.githubusercontent.com/62343878/99427670-ee32b880-28c2-11eb-812e-4f78707463fa.png)
![2020-11-17 10_34_20-Ryujinx 1 0 5727 - Need For Speed™ Hot Pursuit Remastered v1 0 0 (010029B0118E80](https://user-images.githubusercontent.com/62343878/99427702-f985e400-28c2-11eb-886d-732fa45057b9.png)
![2020-11-17 10_34_52-Ryujinx 1 0 5727 - Need For Speed™ Hot Pursuit Remastered v1 0 0 (010029B0118E80](https://user-images.githubusercontent.com/62343878/99427727-00145b80-28c3-11eb-8eb6-60ce9232cffa.png)
![2020-11-17 10_36_32-Ryujinx 1 0 5727 - Need For Speed™ Hot Pursuit Remastered v1 0 0 (010029B0118E80](https://user-images.githubusercontent.com/62343878/99427744-07d40000-28c3-11eb-8bbf-a7d53274e3ac.png)
![2020-11-17 10_37_17-Ryujinx 1 0 5727 - Need For Speed™ Hot Pursuit Remastered v1 0 0 (010029B0118E80](https://user-images.githubusercontent.com/62343878/99427781-11f5fe80-28c3-11eb-8d39-6efae408942f.png)
![2020-11-17 10_38_07-Ryujinx 1 0 5727 - Need For Speed™ Hot Pursuit Remastered v1 0 0 (010029B0118E80](https://user-images.githubusercontent.com/62343878/99427814-1d492a00-28c3-11eb-98fa-9f81ee376426.png)
![2020-11-17 10_39_07-Ryujinx 1 0 5727 - Need For Speed™ Hot Pursuit Remastered v1 0 0 (010029B0118E80](https://user-images.githubusercontent.com/62343878/99427857-276b2880-28c3-11eb-951e-7ce8ec41d624.png)
![2020-11-17 10_40_21-Ryujinx 1 0 5727 - Need For Speed™ Hot Pursuit Remastered v1 0 0 (010029B0118E80](https://user-images.githubusercontent.com/62343878/99427896-318d2700-28c3-11eb-9033-eba3ed74e950.png)
![2020-11-17 10_46_08-Ryujinx 1 0 5727 - Need For Speed™ Hot Pursuit Remastered v1 0 0 (010029B0118E80](https://user-images.githubusercontent.com/62343878/99427930-3ce05280-28c3-11eb-976b-aa22be6913fa.png)
![2020-11-17 10_46_31-Ryujinx 1 0 5727 - Need For Speed™ Hot Pursuit Remastered v1 0 0 (010029B0118E80](https://user-images.githubusercontent.com/62343878/99427962-479ae780-28c3-11eb-86c4-ed2ee1bca70e.png)
![2020-11-17 10_47_00-Ryujinx 1 0 5727 - Need For Speed™ Hot Pursuit Remastered v1 0 0 (010029B0118E80](https://user-images.githubusercontent.com/62343878/99427982-4ff32280-28c3-11eb-884d-b385f69288fb.png)
![2020-11-17 10_47_13-Ryujinx 1 0 5727 - Need For Speed™ Hot Pursuit Remastered v1 0 0 (010029B0118E80](https://user-images.githubusercontent.com/62343878/99428011-54b7d680-28c3-11eb-9749-8d637dd76b3d.png)
![2020-11-17 10_48_47-Ryujinx 1 0 5727 - Need For Speed™ Hot Pursuit Remastered v1 0 0 (010029B0118E80](https://user-images.githubusercontent.com/62343878/99428036-5c777b00-28c3-11eb-8663-c15912bf8edf.png)
![2020-11-17 10_49_28-Ryujinx 1 0 5727 - Need For Speed™ Hot Pursuit Remastered v1 0 0 (010029B0118E80](https://user-images.githubusercontent.com/62343878/99428075-68fbd380-28c3-11eb-814a-0a3a02c73c43.png)
![2020-11-17 10_50_38-Ryujinx 1 0 5727 - Need For Speed™ Hot Pursuit Remastered v1 0 0 (010029B0118E80](https://user-images.githubusercontent.com/62343878/99428124-74e79580-28c3-11eb-89c5-0f98a142b514.png)
![2020-11-17 10_51_00-Ryujinx 1 0 5727 - Need For Speed™ Hot Pursuit Remastered v1 0 0 (010029B0118E80](https://user-images.githubusercontent.com/62343878/99428143-7dd86700-28c3-11eb-97c3-75c7f5cb132e.png)

#### Log file :

[NFSHP.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5555289/NFSHP.zip)

**Comment by Jayinem** [comment]
I only get12-15 fps.

Processor	Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz, (goes up to 4.1GHz) 2400 Mhz, 4 Core(s), 8 Logical Processor(s)
Nvidia GTX 1650 16 GB Ram

**Comment by EmulationFanatic** [comment]
Updated. All previous issues with this game are resolved.

**Comment by viksmir** [comment]
Audio issues persist. The sound is choppy. With 30 FPS locked.

**Comment by amiMohammad** [comment]
This game "Need for Speed Hot Pursuit Remastered v1.0.3" is crashing at start without any warning. Even not showing intro. I have tried everything.

But its playable using YUZU emulator on my PC.

PC Spec:

i5 4590s
RAM 8GB
1030 GT 2GB
Win 11 Pro

**Comment by yogithesymbian** [comment]
> Updated. All previous issues with this game are resolved.

No .. its still on audio bug is choppy . 
Device : 13" Macbook Pro M1 ( 8GB ) with Ryujinx 1.1.898
Game Version 1.0.3
Lock : 30 FPS run well/smooth

**Comment by yogithesymbian** [comment]
https://github.com/Ryujinx/Ryujinx-Games-List/assets/28316296/8f690f06-de4c-49be-a383-f43f586ee201

why video so dark ? 
> its from ffmpeg converter dunno why, m4v to mp4.

**Comment by yogithesymbian** [comment]
almost all maps condition rain and night have glitch . Only carson ridge reservoir and one i forgot there is no glitch at night and thunder . But moatly have glitch on body of car

**Comment by yogithesymbian** [comment]
https://github.com/Ryujinx/Ryujinx-Games-List/assets/28316296/88119bb8-555f-4dd1-991b-74d7153cd130

audio choppy preview

**Comment by adrianmihalko** [comment]
Audio is still choppy. M1

**Comment by amiMohammad** [comment]
> yonfshotpursuitremasteredbug.mp4 
> audio choppy preview

Ryujinx itself is an Nintendo Switch Emulator.

Ryujinx on Normal Windows PC with great hardware, Ryujinx performance is somewhat ok.

Ryujinx on Macbook Pro with "Apple M1 SoC" is like, Emulator inside another Emulator.
So, Ryujinx Emulator on Macbook Pro with "Apple M1 SoC" will perform more like a POTATO PC.   ;(

**Comment by amurgshere** [comment]
Audio issue seems to have changed a bit now, its choppy and horrible irrespective of the volume level in the game now, turning it down doesn't help, its a shame because the video is so smooth and the game play so well if you ignore the audio. 
Really hope we can address this issue... I don't think this has anything to do with performance, as the video is running so smoothly and frame rates are 30  #FPS...

Game Update Version : 1.0.3

Current on master : Latest MACOS Build as at 20/02/2024

Graphics Backend : Vulkan

Hardware Specs :  M1 MacBook Air 16 GB RAM 8 Core GPU, 8 Core CPU

I have a video, but its too big to upload here, 118 MB, is there a video service I can use to share the video?

**Comment by yogithesymbian** [comment]
> Audio issue seems to have changed a bit now, its choppy and horrible irrespective of the volume level in the game now, turning it down doesn't help, its a shame because the video is so smooth and the game play so well if you ignore the audio. Really hope we can address this issue... I don't think this has anything to do with performance, as the video is running so smoothly and frame rates are 30 #FPS...
> 
> Game Update Version : 1.0.3
> 
> Current on master : Latest MACOS Build as at 20/02/2024
> 
> Graphics Backend : Vulkan
> 
> Hardware Specs : M1 MacBook Air 16 GB RAM 8 Core GPU, 8 Core CPU
> 
> I have a video, but its too big to upload here, 118 MB, is there a video service I can use to share the video?


Did you have a test with the whisky (GPTK) PC version?

**Comment by amurgshere** [comment]
> Did you have a test with the whisky (GPTK) PC version?

I have a capable windows PC here, so will give it a test tonight to see, i dont tend to use RyuJinx all that much on my windows PC so didn’t consider testing it. Thanks for the idea.
