### ISSUE TITLE
The Legend of Zelda: Skyward Sword HD - 01002DA013484000

### ISSUE THREAD

**Issue by Connor2803** [Ryujinx/Ryujinx-Games-List#3657]
#### Current on `master` : 1.0.6973

Game runs perfectly, seemingly capped at 60FPS. The only issues are the small graphical bugs that occur with certain particles, such as cut grass flying away, and The Imprisoned's aura. Other than that, the game is completely playable!

#### Last error returned:
Will have to play for a bit more to encounter an error.

#### Screenshots
![ryujinx_capture_2021-07-19_14-28-22](https://user-images.githubusercontent.com/87635341/126122510-5f48bb25-0bd0-412f-949c-470e45b54ea5.png)
![ryujinx_capture_2021-07-19_14-27-45](https://user-images.githubusercontent.com/87635341/126122501-291bbe43-0a3e-4c55-95d2-ab079ca70ca0.png)

**Comment by nashlaga** [comment]
Majority of the audio including music seems to be playing at a lowered bit depth or sample rate,

**Comment by Connor2803** [comment]
I also tried on another PC, this one yielding sub-par results. The title screen didn't have any textures, and the gameplay and cutscenes also had limited textures. Definitely a GPU issue I would say, more linked to my old-as graphics card.

Game Update Version : 1.0.0
Ryujinx Version 1.0.6973
Hardware Specs :
CPU: Intel i5-3340
GPU: ATI 6870
RAM: 8GB DDR3

Title screen:
![ryujinx_capture_2021-07-20_21-13-52](https://user-images.githubusercontent.com/87635341/126333930-636154f4-c464-47ac-b099-2af23a6a6eed.png)
Opening cutscene:
![ryujinx_capture_2021-07-20_21-14-42](https://user-images.githubusercontent.com/87635341/126333940-e85865af-4980-4c02-9f86-bdc407e2e1c9.png)
In Link's Room
![ryujinx_capture_2021-07-20_21-15-18](https://user-images.githubusercontent.com/87635341/126333944-0f84adeb-d7c3-41f6-8204-cddf2e5405ef.png)
![ryujinx_capture_2021-07-20_21-16-18](https://user-images.githubusercontent.com/87635341/126333948-8112f132-9f4a-40b8-97f4-5ecbcbd1f9f3.png)

**Comment by JoachimFlottorp** [comment]
Game Update Version : 1.0.0
Current on master : 1.0.6974

Hardware Specs :
CPU: AMD Ryzen-5-2600
GPU: NVIDIA RTX 3060 Ti
RAM: 32GB

**Comment by umbrellacorp53** [comment]
> Majority of the audio including music seems to be playing at a lowered bit depth or sample rate,

100% agree. I tried every audio setting. Thought it was my imagination so I opened a different emulator and it had much higher audio quality, but I prefer Ryujinx for upscaling...

**Comment by tazzkiller** [comment]
no sound problem with OpenAL on windows for me

**Comment by umbrellacorp53** [comment]
> no sound problem with OpenAL on windows for me

I am also on OpenAL and Windows. Tried all the audio settings, different CPU and Sync settings. Nothing got rid of it. It's not necessarily an obvious problem. Probably depends on your listening device. TV speakers there is barely a difference. High quality headphones and its fairly obvious.

To replicate it, at least where it's most obvious for me, after starting a new game, skip the cutscenes, walk out into the hall, and listen to the music. When woodwind or horn instruments come it during the music it's fairly obvious that the audio is bitcrushed or downsampled. Not sure what's going on, but it sounds low fidelity as if it's emulating bad onboard speakers on a mobile device. As a comparison you can open the exact same scenario in the other Switch emulator and the music is crystal clear and has a wider sound stage.

All in all this is a minor complaint, except that this game (and series) is is known for its beautiful score, and Ryujinx rebuilt their sound emulation from the ground up to be of much higher quality and accuracy. Audio is a huge part of the experience.

**Comment by umbrellacorp53** [comment]
Was going to post Youtube videos for comparison. The difference between the two is still noticeable, most obvious at the very end of the woodwind part, but since this is mostly an issue in the ultra high pitch "hiss" region of the audio it isn't as noticeable on Youtube since they compress the audio and throw out anything above 15khz.

**Comment by 6hj4wezt4ew** [comment]
I'm not sure about the sound _quality_, but I'm running into an issue where the music seems to stop after certain events trigger, such as opening/closing a door.  Running Ryujinx version 1.0.6974 on Windows 10 64-bit, with a Ryzen 5 1500X and GTX 970 plus 32 GB RAM.  I've tried all the different audio backends, but it seems to make no difference.

**Comment by kawuchuu** [comment]
Game runs decently well. Having the same audio quality issues as everyone else, doesn't matter which backend is selected.

Having some graphical issues with various particles not displaying properly:
![image](https://user-images.githubusercontent.com/29061105/126596191-4162d823-ef64-47f8-b3c8-8fb93bb0f7cc.png)

Framerate drops in some areas like Skyloft when looking towards the centre:
![image](https://user-images.githubusercontent.com/29061105/126595539-8a271299-a659-4469-879a-228f16c6636d.png)

Otherwise the framerate is smooth:
![image](https://user-images.githubusercontent.com/29061105/126595607-0f9ac291-9e26-4db1-b647-db7aaad86f95.png)

Running Ryujinx 1.0.6974, Windows 10 64-bit, Ryzen 5 1500X, GTX 1060 6GB, 16GB RAM.

**Comment by FaeTalan** [comment]
Hi. I can't use the right joy-con motion controls, which is key to play this game optimally... I've tried many options without success. Is it a known bug? Has anyone managed to make it work?

**Comment by gdkchan** [comment]
Yes, its fixed by https://github.com/Ryujinx/Ryujinx/pull/2488

**Comment by fabiograssiotto** [comment]
I think I know what is causing the audio issue.
On my system I have a BT headset (JBL). Sometimes the emulator is using it in headset mode (lower audio quality), sometimes in headphone mode (much better).
Try to disable the headset mode on windows - audio sounds as fine as the other emulator to me.

**Comment by jorcip** [comment]
Having some sort of V-Sync when the game is in fullscreen, whether the function is enabled or disabled.
Apart from that, the game is running pretty well... thanks!

**Comment by IamPeacock87** [comment]
The sidequest 'Missing ball' can't be completed because the game crashes when entering the Fortune teller's house.

Tried adjusting every setting possible but always the same outcome.

**Comment by HarshNarayanJha** [comment]
Hey, I can't get the Lanayru Main Generator Puzzle work well. The problem is that the second dial wheel turn (which has to get to the bottom right corner), it just stops at the rightmost end. I keep pressing the `L` key, the `K` key and even both of them together, but it still doesn't work.
On the contrary, the bottom right diagonal sword slash (i.e., by simultaneously pressing `L` and `K` keys) works well!

I'm stuck here!

**Comment by HarshNarayanJha** [comment]
> Maybe try using the pro controller controls if you aren’t already?
> […](#)
> On 15 Aug 2022, at 8:41 pm, Harsh Narayan Jha ***@***.***> wrote: ﻿ Hey, I can't get the Lanayru Main Generator Puzzle work well. The problem is that the second dial wheel turn (which has to get to the bottom right corner), it just stops at the rightmost end. I keep pressing the L key, the K key and even both of them together, but it still doesn't work. On the contrary, the bottom right diagonal sword slash (i.e., by simultaneously pressing L and K keys) works well! I'm stuck here! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

You mean by changing the input settings, right? I tried that too... I don't have Pro Controller Hardware though!

**Comment by ivooc** [comment]
I encountered graphical glitches in the sand on Skyward Sword, in Lanayru Mining Facility. It happens on this room and the boss room. Those places are the only so far that the sand relief is uneven.
![image](https://user-images.githubusercontent.com/44483972/191305474-b4134fe2-df95-4610-b166-1ab99dfd574f.png)

**Comment by HarshNarayanJha** [comment]
> > > Maybe try using the pro controller controls if you aren’t already?
> > > […](#)
> > > On 15 Aug 2022, at 8:41 pm, Harsh Narayan Jha _**@**_.***> wrote: ﻿ Hey, I can't get the Lanayru Main Generator Puzzle work well. The problem is that the second dial wheel turn (which has to get to the bottom right corner), it just stops at the rightmost end. I keep pressing the L key, the K key and even both of them together, but it still doesn't work. On the contrary, the bottom right diagonal sword slash (i.e., by simultaneously pressing L and K keys) works well! I'm stuck here! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.
> > 
> > 
> > You mean by changing the input settings, right? I tried that too... I don't have Pro Controller Hardware though!
> 
> I was having this problem too. Turns out it was a misunderstanding of how the mechanics of the puzzle works. You just have to move and hold the stick in the direction you want the dial to stop and it will move and stop there.

Yes, I finally get past this issue by using an android app as gamepad! Thanks

**Comment by Jotitandres** [comment]
Hello! I'm not sure if i have to do it here but i can't find any other place to mention it.
I play with EmuSAK and download the shaders. But from yesterday once i open this game, the shaders get lost and the play starts to stick. REALLY SLOW!. Open EmuSAK again and the shaders are not there. Redownload and happens again. I do not know if the problem is with Ryujinx or with EmuSAK. Any help?

**Comment by RedKai26** [comment]
Game Name The Legend Of Zelda Skyward Sword HD
Game Update Version: 1,0.1
Emulator Build Version: 1.1.391
Graphics Backend: Vulkan
Hardware Specs:
CPU: i5 1135G7
GPU: Intel® Iris® Xe Graphics
RAM: 8GB
Ok my english is not perfect but i'll try.... The thing is the games has good performance but has this glitch of missing textures around the characters's eyes... well i know it can be fixed by switching to OpenGL but i wanted to adress it.
But the serious one is this glitch when sometimes you open or close a door (it seems that happens with any sound that can "interrumpt" the music) the music just goes silent, here's a video showing both issues: [https://youtu.be/Xia_c8QtMDQ](https://github.com/Ryujinx/Ryujinx-Games-List/issues/url)

Last error returned.
Add the last error in the log if there is any.
e.g.: Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801
I dunno but i'll post the log


#### Screenshots:

*Add screenshots here (preferably on windowed mode) if the game is rendering
![image](https://user-images.githubusercontent.com/119143634/204116051-8da120e5-8222-4403-ac3b-cf8602500a79.png)
.*


#### Log file:

*Add a log file here. 
Can be found in the logs folder, in the same directory as the Ryujinx executable, or through File > Open logs folder.*

[Ryujinx_1.1.391_2022-11-26_19-42-54.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10097362/Ryujinx_1.1.391_2022-

**Comment by skabning** [comment]
> I encountered graphical glitches in the sand on Skyward Sword, in Lanayru Mining Facility. It happens on this room and the boss room. Those places are the only so far that the sand relief is uneven. ![image](https://user-images.githubusercontent.com/44483972/191305474-b4134fe2-df95-4610-b166-1ab99dfd574f.png)
> 
> ```
> Ryujinx version: 1.1.277
> Game version: 1.0.1
> System Specs:
>     OS: Microsoft Windows 10.0.19044 (X64)
>     CPU: AMD Ryzen 5 5600G
>     GPU: NVIDIA RTX 2060
>     RAM: 32GB
> Applied Mods : No
> ```
> 
> Using Vulkan backend, 2x resolution, docked mode, anisotropic filtering 16x, vsync on. Tried changing to OpenGL, native resolution, handheld mode, anisotropic filtering auto, vsync off.

I can confirm this is also happening on the mac build on my M1 Air, running Ventura.

**Comment by pmxzerb** [comment]
> > I encountered graphical glitches in the sand on Skyward Sword, in Lanayru Mining Facility. It happens on this room and the boss room. Those places are the only so far that the sand relief is uneven. ![image](https://user-images.githubusercontent.com/44483972/191305474-b4134fe2-df95-4610-b166-1ab99dfd574f.png)
> > ```
> > Ryujinx version: 1.1.277
> > Game version: 1.0.1
> > System Specs:
> >     OS: Microsoft Windows 10.0.19044 (X64)
> >     CPU: AMD Ryzen 5 5600G
> >     GPU: NVIDIA RTX 2060
> >     RAM: 32GB
> > Applied Mods : No
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Using Vulkan backend, 2x resolution, docked mode, anisotropic filtering 16x, vsync on. Tried changing to OpenGL, native resolution, handheld mode, anisotropic filtering auto, vsync off.
> 
> I can confirm this is also happening on the mac build on my M1 Air, running Ventura. Returning to that area later has some more, even worse graphical issues. I was able to play through it without too many problems, though.

Having the same sand texture issue as the one shown in the screenshot (same room too). Rest of the game was pretty flawless up until that point for me.

My specs:
`Backend: Vulkan, resolution: 2x, anisotropic filtering: auto, docked mode, vsync: on`
```
Ryujinx version: 1.1.503
Game version: 1.0.0
System Specs:
    OS: Microsoft Windows 10.0.19045 Build 19045 (X64)
    CPU: AMD Ryzen 7 5800X
    GPU: NVIDIA GeForce RTX 3080 12GB
    RAM: 16GB
Applied Mods : No
```

**Comment by Seba244c** [comment]
I still have major audio issues using Ryujinx. Tried using YuZu which performed much better. I have recorded my findings in a video linked below. I also found the logs to be spamming some stuff so i have also linked my logs below.


If you want to skip the read there is a 30 thousand lines of ```00:00:18.656 |S| HLE.OsThread.20 ServiceMm SetAndWait: Stubbed. {id: 1 ; frequenceHz: 4294966296 ; timeout: -1}
00:00:18.656 |S| HLE.OsThread.20 ServiceMm Get: Stubbed. {id: 1}```

Video comparison: [https://web-static.sebsa.dk/debug/Audio%20Comparison.mp4](https://web-static.sebsa.dk/debug/Audio%20Comparison.mp4)
Logs: [https://web-static.sebsa.dk/debug/Ryujinx_1.1.643_2023-02-26_13-15-14.log](https://web-static.sebsa.dk/debug/Ryujinx_1.1.643_2023-02-26_13-15-14.log)

**Comment by Seba244c** [comment]
Does anybody know a fix or does anybody wanna help me with a bug report? I don't know weather this is an issue om my end or on Ryujinx's end, so I don't wanna create a bug report.
People with the same issue: [1](https://github.com/Ryujinx/Ryujinx-Games-List/issues/3657#issuecomment-882900231) [2](https://github.com/Ryujinx/Ryujinx-Games-List/issues/3657#issuecomment-884089319) [3](https://github.com/Ryujinx/Ryujinx-Games-List/issues/3657#issuecomment-884602587)

**Comment by noxifoxi** [comment]
@ivooc Glitched sand patches are fixed by Ryujinx/Ryujinx#4483 fixing Ryujinx/Ryujinx#4477
@Seba244c video decoding issue: Ryujinx/Ryujinx#2815

**Comment by turntable97** [comment]
> Having some graphical issues with various particles not displaying properly: ![image](https://user-images.githubusercontent.com/29061105/126596191-4162d823-ef64-47f8-b3c8-8fb93bb0f7cc.png)

Can the broken particles on OpenGL still not be fixed?
Happens especially when cutting grass, standing in front of a waterfall and returning to the sky.

**Comment by NineKain** [comment]
Particles are still bugged on vulkan, 3060ti latest drivers

**Comment by Willyyutrdfcg** [comment]
How I download it?
