### ISSUE TITLE
逆转裁判四五六 王泥喜精选集 (Apollo Justice Ace Attorney Trilogy) - 010020d01b890000

### ISSUE THREAD

**Issue by teszNU** [Ryujinx/Ryujinx-Games-List#4862]
### Game Name

逆转裁判四五六 王泥喜精选集 (Apollo Justice Ace Attorney Trilogy)

### Game Update Version

1.0.1

### Emulator Build Version

1.1.1125

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: AMD A8-7500 Radeon R7, 10 Compute Cores 4C+6G
- ##### GPU:  NVIDIA GeForce GT 1030 (Dell OEM)
- ##### GPU Driver version: 546.33.0.0
- ##### RAM: 8GB

### Game State

OSVER: Microsoft Windows 11 23H2 22631.3007
**_”一斤鸭梨！“_**
Runtime fine and not found any problems.

### Screenshots

![屏幕截图 2024-01-25 082158](https://github.com/Ryujinx/Ryujinx-Games-List/assets/61547678/c86b82e3-8ca1-4804-844e-3e5897bd7705)
![屏幕截图 2024-01-25 104846](https://github.com/Ryujinx/Ryujinx-Games-List/assets/61547678/9f536262-8d3c-4bff-bff3-793c23fb1947)

### Log File

[Ryujinx_1.1.1125_2024-01-25_09-09-28.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14046417/Ryujinx_1.1.1125_2024-01-25_09-09-28.log)

**Comment by macvip** [comment]
**Game Name**
逆转裁判四五六 王泥喜精选集 (Apollo Justice Ace Attorney Trilogy)

**Game Update Version**
1.0.1

**Emulator Build Version**
1.1.1139

**Graphics Backend**
Vulkan

**Hardware Specs**
- CPU: Apple M1 Max
- GPU: Apple M1 Max

**Game State**
Crash at some spec scene

**Crash Log:**
[Ryujinx_1.1.1139_2024-01-27_07-07-44.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14070159/Ryujinx_1.1.1139_2024-01-27_07-07-44.log)

**Save:**
[0.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/14070288/0.zip)

**Comment by gdkchan** [comment]
> Crash at some spec scene

What is the exact scene where it is supposed to crash? Maybe you can show a picture on the moments before the crash?

**Comment by macvip** [comment]
> > Crash at some spec scene
> 
> What is the exact scene where it is supposed to crash? Maybe you can show a picture on the moments before the crash?

Please unzip 0.zip and import the saved data, use this saved slot:
![1](https://github.com/Ryujinx/Ryujinx-Games-List/assets/6308663/a251e30b-c408-474d-98c8-0c220362f9cc)
Then click and click, until this scene, one more click, and it crashes:
![2](https://github.com/Ryujinx/Ryujinx-Games-List/assets/6308663/f3a39434-227c-4818-a416-60606b89c2b2)

**Comment by wjddbstl** [comment]
I'm in the same situation at the moment. I think the game crashes in every part where there's a 3d animation production. Who knows how to solve it?

**Comment by wjddbstl** [comment]
a crash occurs Among the evidence from the first episode, when you press a wine bottle, the pendant scene of Naruhodo, and when O'Doroki sees a rotating chair.

**Comment by wjddbstl** [comment]
I'm new to GitHub and I'm not sure how to fix it. Do I need to modify the coding?

**Comment by daguiar1609** [comment]
There's a problem in the second case of the first game where it doesn't let you ink the footprint and instead shows some messed up graphics. 
Here's a picture:
![imagem_2024-01-29_162154557](https://github.com/Ryujinx/Ryujinx-Games-List/assets/116581047/99ac45a4-60c9-4d3a-a89b-92c43a4ac0e0)

**Comment by retropieuser** [comment]
> > > Crash at some spec scene
> > 
> > 
> > What is the exact scene where it is supposed to crash? Maybe you can show a picture on the moments before the crash?
> 
> Please unzip 0.zip and import the saved data, use this saved slot: ![1](https://private-user-images.githubusercontent.com/6308663/300148807-a251e30b-c408-474d-98c8-0c220362f9cc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NTE4MTMsIm5iZiI6MTcwNjY1MTUxMywicGF0aCI6Ii82MzA4NjYzLzMwMDE0ODgwNy1hMjUxZTMwYi1jNDA4LTQ3NGQtOThjOC0wYzIyMDM2MmY5Y2MuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzBUMjE1MTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTFlY2QzMjYwZjQ0NTE3MWQ2NDZlNDA1ZjVkY2JiZmU4YjA5NzIyNmUyNThjNjQxMzUyMGI1OGMxYThmODQ2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JcKV9uDTMzWSy2LTNM8FL9EyAc8yHcAOaWCeJXM5syw) Then click and click, until this scene, one more click, and it crashes: ![2](https://private-user-images.githubusercontent.com/6308663/300148917-f3a39434-227c-4818-a416-60606b89c2b2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NTE4MTMsIm5iZiI6MTcwNjY1MTUxMywicGF0aCI6Ii82MzA4NjYzLzMwMDE0ODkxNy1mM2EzOTQzNC0yMjdjLTQ4MTgtYTQxNi02MDYwNmI4OWMyYjIuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzBUMjE1MTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjY1ZDE3MjljNTYxYzI0M2Q3NDk1MTlmNjk2ZWFiYjc5NWQ5MGNlOTRkODI1OWRiMmJmMTEzYzllM2RkMDAwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TddPEl4y5u1slZBhj0U-gU_Sh4fO7QoMhoQHDpKawUI)

I also get this same error using Ryujinx on MacBook M1 with Vulkan

**Comment by retropieuser** [comment]
Can the label be changed from playable please? Does seem to crash anytime the 3D item GUI comes into play. Also with Dual Destinies, the 3D models of the characters flicker as well. So it's not really playable just yet

**Comment by gdkchan** [comment]
> Can the label be changed from playable please? Does seem to crash anytime the 3D item GUI comes into play. Also with Dual Destinies, the 3D models of the characters flicker as well. So it's not really playable just yet

That only happens on macOS (or OpenGL, but I don't think anyone uses that anymore). I don't think we currently label games based on macOS state alone. If you don't want to wait until the fix is merged, you can just use the build on the PR https://github.com/Ryujinx/Ryujinx/pull/6190#issuecomment-1913411210 (expand `Experimental GUI (Avalonia)` dropdown, get the one ending with `macos_universal`).

**Comment by WWIA7062** [comment]
> I'm in the same situation at the moment. I think the game crashes in every part where there's a 3d animation production. Who knows how to solve it?

on windows for me on the US version it works just fine (it ran 3d way better then yuzu and I saw no issues)

**Comment by AKHELOsa** [comment]
Is there any tutorial or step by step to fix it? Because i use the GUI avalonia version but the game still crashed

**Comment by Alicelas** [comment]
Some small bug. There will be some small gaps in many character image, and some character movements will appear abnormally jagged under the native resolution.
![20240611145137](https://github.com/Ryujinx/Ryujinx-Games-List/assets/51156839/a209571f-a8af-4da4-958f-a6d4da7d3566)

**Comment by eXhumer** [comment]
I was able to play the title fine before (version 1.1.1330) except for the section where you have to get boot prints in chapter 2 of the first game. That seems to have caused the emulator/game to crash after a few seconds. That section seems to somewhat work with the last build of Yuzu EA 4176 however (although there were graphical issues in Yuzu like reported by @daguiar1609).

However, since the 1.1.1334 update, the game straight up refuses to load. The emulator gets past the "Compiling PTC" and then crashes the emulator after 10-20 seconds. The log doesn't appear to provide much information. I am running the Linux build on a Steam Deck OLED with Vulkan backend. I have installed the latest available firmware at the time of this comment (18.1.0). Any help would be appreciated.

I have tested other games (Prince of Persia: The Lost Crown & Red Dead Redemption) and they seem to run without any issue.

[Ryujinx_1.1.1334_2024-06-17_03-00-20.log](https://github.com/user-attachments/files/15864629/Ryujinx_1.1.1334_2024-06-17_03-00-20.log)

**Comment by gdkchan** [comment]
FWIW it is still working fine here.
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/5624669/137bb6dd-b796-4fb7-bb2e-f6292e12f405)
You can try:
- Switching to OpenGL to check if its the graphics driver that is crashing.
- Clearing PPTC/shader cache in case they got corrupted somehow.
- Temporarily removing your save in case it got corrupted.

**Comment by eXhumer** [comment]
OK, seems like nuking the Ryujinx folder inside ~/.config and redoing the firmware / keys seems to have fixed it for me.

**Comment by Alicelas** [comment]
I figured everything out. The main problem occurred in Apollo Justice 4. Under the native resolution of the console mode, some of the character's movements will be rendered at the resolution of the handheld mode, so some movements have a glitchy feel. This problem can be solved by improving the resolution. To solve the problem, 4X is the best, but it will cause another problem. As I said above, there will be gaps in the character drawing.

But again, these problems do not affect the gameplay. I just want to understand why there are problems.
